
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { CartProvider } from "@/contexts/CartContext";

export const metadata = {
  title: "BIOPROX",
  description: "Generated by create next app",
};

export default function MarketingLayout({ children }) {
  return (
    <>
      <CartProvider>
        <Navbar />
        {children}
        <Footer />
      </CartProvider>
    </>
  )
}
